---
# - name: apache
#   src: https://github.com/alexandrubau/ansible-apache.git
# - name: nginx
#   src: https://github.com/alexandrubau/ansible-nginx.git
- name: php
  src: https://github.com/alexandrubau/ansible-php.git