---
- name: Create folder
  file:
    path: "{{ _adminer_download_dest | dirname }}"
    state: directory
  notify: site-permissions

- name: Download
  get_url:
    url: "{{ _adminer_download_url }}"
    dest: "{{ _adminer_download_dest }}"
  notify: site-permissions

- name: Download theme
  get_url:
    url: "{{ _adminer_theme_url }}"
    dest: "{{ _adminer_theme_dest }}"
  notify: site-permissions

- name: Add apache site
  template:
    src: ./templates/adminer.apache.conf.j2
    dest: /etc/apache2/sites-available/adminer.conf
  when: _apache_role is defined

- name: Enable apache site
  file:
    src: /etc/apache2/sites-available/adminer.conf
    dest: /etc/apache2/sites-enabled/adminer.conf
    state: link
  when: _apache_role is defined
  notify: restart-webserver

- name: Add nginx site
  template:
    src: ./templates/adminer.nginx.conf.j2
    dest: /etc/nginx/sites-available/adminer.conf
  when: _nginx_role is defined

- name: Enable nginx site
  file:
    src: /etc/nginx/sites-available/adminer.conf
    dest: /etc/nginx/sites-enabled/adminer.conf
    state: link
  when: _nginx_role is defined
  notify: restart-webserver
